image: php:7.4

# Define pipeline stages
stages:
  - code-quality

# Let's build before deploy
before_script:
  - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/ -p
  - ls -ltr

# Code quality is matter
code-fix:
  stage: code-quality
  script:
    - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA -p
    - pwd && echo build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcbf-report.txt;
    - phpcbf --standard=PSR12 --error-severity=1 --warning-severity=8 --extensions=php *.php ./src/* --report=code --report-file=build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcbf-report.txt --runtime-set ignore_errors_on_exit 1 --runtime-set ignore_warnings_on_exit 1
    - phpcs --standard=PSR12 --error-severity=1 --warning-severity=8 --extensions=php *.php ./src/* --report=code --report-file=build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcs-report.txt
  artifacts:
    paths:
      - build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcbf-report.txt
      - build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcs-report.txt
  allow_failure: false
