variables:
  STAGING_PATH: "/var/www/html/000_backendApps/otoedi-migration"
  PRODUCTION_PATH: "/var/www/html/000_backendApps/otoedi-migration"

image: php:7.4

# Define pipeline stages
stages:
  - code-quality
  - deploy-staging
  - deploy-production

# Let's build before deploy
before_script:
  - mkdir -p build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/$CI_ENVIRONMENT_SLUG/
  - ls -ltr

# Code quality is matter
code-fix:
  stage: code-quality
  script:
    - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA -p
    - phpcbf --standard=PSR12 --error-severity=1 --warning-severity=8 --extensions=php *.php ./src/*
  allow_failure: true

# Code quality is matter
code-check:
  stage: code-quality
  script:
    - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA -p
    - phpcs --standard=PSR12 --error-severity=1 --warning-severity=8 --extensions=php *.php ./src/* --report=full --report-file=build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/phpcs-report-$CI_COMMIT_SHORT_SHA.txt
  artifacts:
    paths:
      - build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/phpcs-report.txt

deploy-staging:
  stage: deploy-staging
  script:
    - echo "Deploying to staging server"
    - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG -p
    - rsync -va . build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG/ --exclude=*.config-production.json --exclude=*.config-development.json --exclude=build --exclude=.git
    - rsync -arve ssh build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG/. nginx@10.1.1.90:STAGING_PATH --delete
    - ssh -tt nginx@10.1.1.90 "composer && php73 /usr/local/bin/composer -d$STAGING_PATH install --no-interaction --profile --prefer-dist --optimize-autoloader --no-dev"

  artifacts:
    paths:
      - build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/$CI_ENVIRONMENT_SLUG/
    expire_in: 1 week
  environment:
    name: staging
  allow_failure: false
  only:
    - master

deploy-production:
  stage: deploy-production
  script:
    - echo "Deploying to production server"
    - mkdir build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG -p
    - rsync -va . build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG/ --exclude=*.config-staging.json --exclude=*.config-development.json --exclude=build --exclude=.git
    - rsync -arve ssh build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_ENVIRONMENT_SLUG/. nginx@10.1.1.70:$PRODUCTION_PATH --delete
    - ssh -tt nginx@10.1.1.74 "composer && php74 /usr/local/bin/composer -d$PRODUCTION_PATH install --no-interaction --profile --prefer-dist --optimize-autoloader --no-dev"

  artifacts:
    paths:
      - build/$CI_COMMIT_REF_NAME$CI_COMMIT_TAG/$CI_COMMIT_SHORT_SHA/$CI_ENVIRONMENT_SLUG/
    expire_in: 1 week
  environment:
    name: production
  allow_failure: false
  only:
    - master

